
export enum WorkflowStatus {
    DRAFT = "DRAFT",
    PUBLISHED_LOCAL = "PUBLISHED_LOCAL",
    PUBLISHED_STORE = "PUBLISHED_STORE"
}


export enum WorkflowType {
    WEBSCRAPPER = "WEB_SCRAPPER",
    WEB_AUTOMATION_TESTING = "WEB_AUTOMATION_TESTING",
    COMMON_APP_INTEGRATION = "COMMON_APP_INTEGRATION"
}