name : Auto merge main-backup with main

on: 
  push:
    branches:
      - main


jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: ctions/checkout@v4

    - name: Setup Git
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

    - name: Fetch All branches
      run: git fetch --all

    - name: Merge main branch into main-backup
      run: |
        git checkout main
        git merge main-backup --no-edit

    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
